[SELC-3003] fix: Sorting institutions list for PT alphabetically
pagopa/selfcare-dashboard-frontend pull request #639
Opened 2023-11-22 10:13 UTC by OraldoDoci

#### List of Changes
Sorting institutions list for PT alphabetically

#### Motivation and Context
In dashboard PT view allow the user to order in alphabeticall order by pressing the arrow icon above the institution name.

#### How Has This Been Tested?
Tested locally 

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-11-22 14:16 UTC, loremedda requested changes

2023-11-22 14:16 UTC, loremedda commented on src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
> +
The logic is quite correct, it can be improved

2023-11-22 14:16 UTC, loremedda commented on src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
You can manage all in the handleSort method

2023-11-22 14:16 UTC, loremedda commented on src/pages/dashboardTechnologyPartnerPage/DashboardTablePT.tsx
> +
It will always be institutionName (there is only that)

Checking the string data is not necessary

2023-11-23 11:31 UTC, loremedda commented
OK

2023-11-23 13:28 UTC, gianmarcoplutino approved these changes

2023-11-23 13:29 UTC, loremedda approved these changes

2023-11-23 13:29 UTC, merged