fixed search party placeholder style
pagopa/selfcare-dashboard-frontend pull request #86
Opened 2021-12-22 13:35 UTC by esignore

2021-12-22 14:38 UTC, rodoviti approved these changes
LGTM

2021-12-23 08:21 UTC, antonioT90 requested changes

2021-12-23 08:21 UTC, antonioT90 commented on src/components/partySelectionSearch/PartySelectionSearchInput.tsx
> +            textTransform: 'capitalize',
```suggestion
            paddingLeft: '16px',
```

2021-12-23 08:39 UTC, antonioT90 approved these changes

2021-12-23 08:39 UTC, merged